export const ADD_PRODUCT= "ADD_PRODUCT";
export const FAIL_PRODUCT= "FAIL_PRODUCT";
export const LOAD_PRODUCT= "LOAD_PRODUCT";
export const GET_PRODUCTS= "GET_PRODUCTS";
export const GET_PRODUCT= "GET_PRODUCT";

export const FILTER_PRODUCT= "FILTER_PRODUCT";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";